Add kelp based rrq object store
mrc-ide/rrq.kelp pull request #1
Opened 2021-06-18 16:18 UTC by r-ash

2021-06-21 10:28 UTC, r-ash commented on .github/workflows/R-CMD-check.yaml
> +          sudo apt-get install -y libcurl4-openssl-dev
Any better way to deal with this than manually? Problem is this requires `kelp` which requires `httr` which needs this lib. But I think because `kelp` being installed via `remotes` it doesn't successfully install dependencies? Solution put `kelp` on that drat?

2021-06-21 10:57 UTC, richfitz requested changes
Some thoughts here.

The docker build is totally fine to remove - I've done that on most things with the template and we should make it an option in the template

2021-06-21 10:57 UTC, richfitz commented on .github/workflows/R-CMD-check.yaml
> +          sudo apt-get install -y libcurl4-openssl-dev
This _should_ be done automatically as part of the action, but I've had to do this myself too

2021-06-21 10:57 UTC, richfitz commented on R/kelp_store.R
> +        private$con$SET(rrq_kelp_hash_id(private$queue_id, object_hash),
We might bulk add these, both across the for loop and the pair of adds (via pipeline). `MSET` instead of `SET` and `SADD` already accepts a vector. If you're concerned about failure, some error handling could be added

2021-06-21 10:57 UTC, richfitz commented on R/kelp_store.R
> +      lapply(hash, function(object_hash) {
`con$MGET(hash)` would get you all the hashes at once

2021-06-21 10:57 UTC, richfitz commented on R/kelp_store.R
> +          private$kelp$download_object(kelp_id, collection = private$queue_id))
I thought `download_object` deserialised already? Or is this because we're uploading raw? We should support this better I think in kelp, otherwise you've double-serialised

2021-06-21 10:57 UTC, richfitz commented on R/kelp_store.R
> +        kelp_id <- private$con$GET(
mget here, then one pipeline

2021-06-24 16:49 UTC, richfitz requested changes
This is great, some small comments here. I expect actual use will shake out more though...

2021-06-24 16:49 UTC, richfitz commented on .github/workflows/test-coverage.yaml
> +          remotes::install_github("mrc-ide/kelp")
these two should not be needed as you have them in the description

2021-06-24 16:49 UTC, richfitz commented on R/kelp_store.R
> +      private$con$pipeline(.commands = c(
can you rewrite this so the commands is a variable before the pipeline call - having trouble reading at present

2021-06-24 16:49 UTC, richfitz commented on R/keys.R
> +  sprintf("rrq:kelp:%s:hash::%s:id", queue_id, hash)
why two colons here (after `hash`)

2021-06-25 09:14 UTC, r-ash commented on R/keys.R
> +  sprintf("rrq:kelp:%s:hash::%s:id", queue_id, hash)
Oops

2021-07-05 07:58 UTC, richfitz requested changes
Small things here, then let's find out of it works :)

2021-07-05 07:58 UTC, richfitz commented on R/kelp_store.R
> +##' @title SeaweedFS-based rrq offload
Should be exported?

2021-07-05 07:58 UTC, richfitz commented on R/kelp_store.R
> +      })
```suggestion
      lapply(kelp_ids, private$kelp$download_object, collection = private$queue_id)
```

2021-07-05 07:58 UTC, richfitz commented on R/kelp_store.R
> +      })
```suggestion
      lapply(kelp_ids, private$kelp$delete, collection = private$queue_id)
```

2021-07-06 10:47 UTC, richfitz approved these changes

2021-07-06 10:47 UTC, merged